### ISSUE TITLE
Comment:Step-Basic-Rest-client

### ISSUE THREAD

**Issue by pedrogk** [feathersjs/feathers-guide#2]
Comment:Step-Basic-Rest-client

"const app = feathers() instantiates a Feathers client."
should be
"const feathersClient = feathers() instantiates a Feathers client."

**Comment by eddyystop** [comment]
Are you referring to
```js
module.exports = () => {
  const app = feathers()
    .use(compress())
```

If so, we are using `app` on the server because it is the application, and we use `feathersClient` on the client because on the client Feathers is not the application, just the services component of it.

Let's move any further discussion of this to `feathers-docs` as this guide has now been published there.

**Comment by eddyystop** [comment]
Ah, I found what you were referring to. Thanks! Docs have been updated.
